[[apps]]
title = "Unigine Heaven"
icon_png_path = "https://games-on-whales.github.io/wildlife/apps/unigine-benchmark/assets/heaven-icon.png"

[apps.runner]
type = "docker"
name = "WolfUnigineHeaven"
image = "ghcr.io/games-on-whales/unigine-benchmark:edge"
env = [
    "UNIGINE_BENCHMARK=heaven",
    "RUN_SWAY=true",
    "GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*"
]
devices = []
mounts = []
ports = []
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "Privileged": false,
    "CapAdd": ["SYS_ADMIN", "SYS_NICE", "SYS_PTRACE", "NET_RAW", "MKNOD", "NET_ADMIN"],
    "SecurityOpt": ["seccomp=unconfined", "apparmor=unconfined"],
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
\
"""

[[apps]]
title = "Unigine Valley"
icon_png_path = "https://games-on-whales.github.io/wildlife/apps/unigine-benchmark/assets/valley-icon.png"

[apps.runner]
type = "docker"
name = "WolfUnigineValley"
image = "ghcr.io/games-on-whales/unigine-benchmark:edge"
env = [
    "UNIGINE_BENCHMARK=valley",
    "RUN_SWAY=true",
    "GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*"
]
devices = []
mounts = []
ports = []
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "Privileged": false,
    "CapAdd": ["SYS_ADMIN", "SYS_NICE", "SYS_PTRACE", "NET_RAW", "MKNOD", "NET_ADMIN"],
    "SecurityOpt": ["seccomp=unconfined", "apparmor=unconfined"],
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
\
"""

[[apps]]
title = "Unigine Superposition"
icon_png_path = "https://games-on-whales.github.io/wildlife/apps/unigine-benchmark/assets/superposition-icon.png"

[apps.runner]
type = "docker"
name = "WolfUnigineSuperposition"
image = "ghcr.io/games-on-whales/unigine-benchmark:edge"
env = [
    "UNIGINE_BENCHMARK=superposition",
    "RUN_SWAY=true",
    "GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*"
]
devices = []
mounts = []
ports = []
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "Privileged": false,
    "CapAdd": ["SYS_ADMIN", "SYS_NICE", "SYS_PTRACE", "NET_RAW", "MKNOD", "NET_ADMIN"],
    "SecurityOpt": ["seccomp=unconfined", "apparmor=unconfined"],
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
\
"""
