version: "3"

services:
  wolf:
    image: ghcr.io/games-on-whales/wolf:alpha
    runtime: ${DOCKER_RUNTIME}
    ports:
      - "47984:47984/tcp"
      - "47989:47989/tcp"
      - "48010:48010/tcp"
      - "47998-48000:47998-48000/udp"
    privileged: true
    ipc: ${SHARED_IPC}
    volumes:
      - ${XORG_SOCKET}:/tmp/.X11-unix
      - ${PULSE_SOCKET_HOST}:/tmp/pulse/
      - ${DBUS}:/run/dbus:ro
      - ${local_state}/.config/wolf:/wolf/cfg
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - config/common.env
      - config/xorg.env
      # run-gow: gpu_env
    environment:
      # GST_DEBUG_DUMP_DOT_DIR: /dbg
      LOG_LEVEL: "INFO" # Wolf: Set to DEBUG to print more
      GST_DEBUG: "2" # Gstreamer: 2 logs all warnings and errors, set to 4 to see debug information
      XDG_RUNTIME_DIR: "/tmp/.X11-unix"
      PULSE_SERVER: "unix:/tmp/pulse/pulse-socket"

volumes:
  udev:
