#!/bin/bash

set -e

source /opt/gow/bash-lib/utils.sh

if [ -z "$DISPLAY" ]; then
    gow_log "FATAL: No DISPLAY environment variable set.  No X."
    exit 13
fi

# Taken from https://gist.github.com/tullmann/476cc71169295d5c3fe6
MAX=120 # About 120 seconds
CT=0
while ! xdpyinfo >/dev/null 2>&1; do
    sleep 1s
    CT=$(( CT + 1 ))
    if [ "$CT" -ge "$MAX" ]; then
        gow_log "FATAL: $0: Gave up waiting for X server $DISPLAY"
        exit 11
    fi
done
