[[apps]]
start_virtual_compositor = true
title = 'Anki'

    [apps.runner]
    base_create_json = '''{
      "HostConfig": {
        "IpcMode": "host",
        "CapAdd": ["NET_RAW", "MKNOD", "NET_ADMIN", "SYS_ADMIN", "SYS_NICE"],
        "Privileged": false,
        "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
      }
    }'''

    devices = []
    env = ['RUN_SWAY=1', 'GOW_REQUIRED_DEVICES=/dev/input/event* /dev/dri/* /dev/nvidia* /var/lutris/']
    image = 'ghcr.io/games-on-whales/anki:edge'
    mounts = []
    name = 'WolfAnki'
    ports = []
    type = 'docker'