== Debian/Ubuntu

When you already have a desktop environment you can still run our docker
containers alongside normal desktop applications.

Can you tell that Steam is runnning in Docker?

=== How it works

You can easily run Sunshine and Steam on Docker without having to
install a single package on your desktop! We all know
https://youtu.be/0506yDSgU7M?t=619[how catastrophic that can be]. The
idea is to use Xorg and PulseAudio from the host OS and mount only the
sockets to the Docker containers.

IMPORTANT: In order for Sunshine to stream your desktop you have to *have a monitor plugged* (or use a dummy plug) and *a user logged in* (or enable https://help.ubuntu.com/community/AutoLogin[autologin])

=== Configuration

Before launching GoW for the first time, you'll want to set up your environment
to your tastes.  Edit the `.env` file to set `local_state` and `TIME_ZONE`, and
also be sure to uncomment the "host" config section towards the bottom.  You
might need to tweak the socket locations or `XORG_DISPLAY` based on your
system.

=== Launching

[source,bash]
----
sudo docker-compose -f docker-compose.yml -f [application].yml pull
sudo docker-compose -f docker-compose.yml -f [application].yml up
----

Currently supported apps are `steam`, `retroarch`, and `firefox`, but you can
add any others you'd like.  Use the existing files as a guide.

