== Debian/Ubuntu

When you already have a desktop environment you can still run our docker
containers alongside normal desktop applications.

Can you tell that Steam is runnning in Docker?

=== How it works

You can easily run Sunshine and Steam on Docker without having to
install a single package on your desktop! We all know
https://youtu.be/0506yDSgU7M?t=619[how catastrophic that can be]. The
idea is to use Xorg and PulseAudio from the host OS and mount only the
sockets to the Docker containers.

IMPORTANT: In order for Sunshine to stream your desktop you have to *have a
monitor plugged* (or use a dummy plug) and *a user logged in* (or enable
https://help.ubuntu.com/community/AutoLogin[autologin])

=== Configuration

Before launching GoW for the first time, you'll want to set up your environment
to your tastes.  Be sure to edit the `user.env` file to set `local_state` and
`TIME_ZONE`.  You might need to tweak the socket locations or `XORG_DISPLAY`
in `env/host-desktop.env` based on your system.

=== Launching

To launch Games on Whales, you can use the `run-gow` script.  See the usage
message (`run-gow --help`) for full details. Some examples follow:

[source,bash]
----
sudo run-gow --gpu nvidia --app retroarch pull
sudo run-gow --gpu nvidia --app retroarch up
----

Currently supported apps are `steam`, `retroarch`, and `firefox`, but you can
add any others you'd like.  Use the existing files as a guide.

=== Connecting

Connect over Moonlight by manually adding the IP address of the PC
running the Docker container. To validate the PIN you can use the
Sunshine web interface (at `https://<IP>:47990/` default username:
`admin`, password: `admin`) or directly calling:
`curl <IP>:47989/pin/<PIN>`.

From Moonlight open the `Desktop` app, from there you should be able to
see your X11 apps running!

=== Next steps

* Checkout the
xref:troubleshooting.adoc[troubleshooting]
page if anything is not working on your side
* Check out how to configure and use your GPU in order to get HW
acceleration (if you have one)
