== Debian/Ubuntu instructions

TIP: Make sure to checkout the
xref:overview.adoc[Overview]
first.

=== Requirement: uinput

This is a required kernel module in order for Sunshine to manage and
create virtual devices (mouse, joypad, etc.).

Make sure that `/dev/uinput` is present in the host.

[source,bash]
----
ls -la /dev/uinput
crw------- 1 root root 10, 223 Jul 15 11:46 /dev/uinput
----

=== Quickstart

IMPORTANT: In order for Sunshine to stream your desktop, you have to *have a monitor plugged* (or use a dummy plug).

==== Environment setup

Before launching GoW for the first time, you'll want to set up your environment
to your tastes.  Edit the `.env` file to set `local_state` and `TIME_ZONE`, and
also be sure to uncomment the "headless" config section towards the bottom.

[source,bash]
----
git clone https://github.com/games-on-whales/gow.git
cd gow
mkdir local_state
sudo docker-compose -f docker-compose.yml -f compose/headless.yml -f [application].yml pull
sudo docker-compose -f docker-compose.yml -f compose/headless.yml -f [application].yml up
----

Currently supported apps are `steam`, `retroarch`, and `firefox`, but you can
add any others you'd like.  Use the existing files as a guide.

Connect over Moonlight by manually adding the IP address of the PC
running the Docker container. To validate the PIN you can use the
Sunshine web interface (at `https://<IP>:47990/` default username:
`admin`, password: `admin`) or directly calling:
`curl <IP>:47989/pin/<PIN>`.

From Moonlight open the `Desktop` app, from there you should be able to
see your X11 apps running!

=== Next steps

* Checkout the
xref:troubleshooting.adoc[troubleshooting]
page if anything is not working on your side
* Check out how to configure and use your GPU in order to get HW
acceleration (if you have one)
