== unRAID

unRAID before version 6.11.0-rc3 is missing the required `uinput` kernel module
out of the box. If you are using an older version, we recommend installing the
https://github.com/ich777/unraid-uinput[uinput plugin]

We are working to build our own unRAID plugin to enable easily starting, stopping, and installing new containers, but for now you'll need to use the `run-gow` script.

=== Pre-requisites

IMPORTANT: In order for Sunshine to be able to stream your desktop, you must meet the xref:monitor.adoc[Monitor requirements].

While a dedicated GPU isn’t strictly necessary (Sunshine does support SW
encoding) it’s highly recommended.

==== docker-compose

unRAID doesn't come with `docker-compose`, but you can easily install it by installing the https://forums.unraid.net/topic/114415-plugin-docker-compose-manager/[docker-compose manager] plugin.

==== Nvidia

If you have a Nvidia GPU you’ll have to also install the
https://forums.unraid.net/topic/98978-plugin-nvidia-driver/[nvidia-driver
plugin]

==== AMD

Users reported in the Discord channel that AMD works out of the box
without having to install any additional driver.

=== Installing GOW

Let’s start by cloning the project locally:

TIP: This will run on your current folder, if you want to keep the repo on the array storage you should first move to the desired folder with: `cd /mnt/user/<some/path/to/gow>`

[source,bash]
----
git clone https://github.com/games-on-whales/gow.git
cd gow
mkdir local_state
----

TIP: On unRAID, the `local_state` folder you just created will be owned by
`root`, and it may not be writable from the containers launched by GoW, which
mostly do _not_ run as `root`. Until GoW has support for changing the UID
inside the containers, you may need to `chmod 777 local_state` to make sure
anyone can write to it.

Now it’s time to download the containers prebuilt images:

[source,bash]
----
run-gow --platform headless --app [appname] pull
----

Currently supported applications include `steam`, `retroarch`, and `firefox`,
but you can add any others that you like. Use the existing ones as examples to
create your own YAML file.

IMPORTANT: Nvidia users: be sure to add `--gpu nvidia` to your `run-gow` command.

[source,bash]
----
run-gow --platform headless --app [application] up -d # start the containers in background
----

This will take some time to start; you can check the status using:
`run-gow --platform headless --app [application] ps`. If one or more containers are
stopped, you can
check the logs using: `run-gow --platform headless --app [application] logs -f`.

=== Accessing GOW

If all the containers are up and running, connect over
https://moonlight-stream.org/[Moonlight] by manually adding the IP
address of the Unraid Host. +
To validate the PIN you can use the Sunshine web interface (at
`https://<IP>:47990/` default username: `admin`, password: `admin`) or
directly calling: `curl <IP>:47989/pin/<PIN>`.

From Moonlight open the `Desktop` app, from there you should be able to
see your X11 apps running!

=== Errors, issues?

* Checkout the xref:troubleshooting.adoc[troubleshooting] page first
* https://github.com/games-on-whales/gow/issues/new[Open an issue on Github]
* Reach out on the dedicated `#unraid` channel on https://discord.gg/kRGUDHNHt2[Discord]
