== Unraid

Unraid is missing the required `uinput` kernel module out of the box. We
have created https://github.com/games-on-whales/unraid-plugin[a plugin]
that adds that and we automated the builds using Github Actions.

We are working to add more support so that you can run GOW easily via
the plugin, for now, you’ll have to manually run the
`docker-compose.yml`.

=== Pre-requisites

IMPORTANT: In order for Sunshine to stream your desktop you have to *have a monitor plugged* (or use a dummy plug).

While a dedicated GPU isn’t strictly necessary (Sunshine does support SW
encoding) it’s highly recommended.

==== Nvidia

If you have a Nvidia GPU you’ll have to also install the
https://forums.unraid.net/topic/98978-plugin-nvidia-driver/[nvidia-driver
plugin]

==== AMD

Users reported in the Discord channel that AMD works out of the box
without having to install any additional driver.

=== Installing GOW

Now that `uinput` is installed via the plugin, it’s time to run GOW via
Docker. +
Let’s start by cloning the project locally:

TIP: This will run on your current folder, if you want to keep the repo on the array storage you should first move to the desired folder with: `cd /mnt/user/<some/path/to/gow>`

[source,bash]
----
git clone https://github.com/games-on-whales/gow.git
cd gow
mkdir local_state
----

Since GOW it’s a composition of multiple docker containers we use
https://docs.docker.com/compose/[`docker-compose`] in order to manage
and spin them up, let’s install it:

[source,bash]
----
curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64 --output /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
----

If all went well you should be able to run: `docker-compose --version`.

Now it’s time to download the containers prebuilt images:

[source,bash]
----
docker-compose pull
----

And start it!

IMPORTANT: Nvidia users: before running it you should modify `DOCKER_RUNTIME=` to `DOCKER_RUNTIME=nvidia` option in the `.env` file

[source,bash]
----
docker-compose up -d # start the containers in background
----

This will take a some time to start, you can check the status using:
`docker-compose ps` in case one or more containers are stopped you can
check the logs using: `docker-compose logs --follow`.

=== Accessing GOW

If all the containers are up and running, connect over
https://moonlight-stream.org/[Moonlight] by manually adding the IP
address of the Unraid Host. +
To validate the PIN you can use the Sunshine web interface (at
`https://<IP>:47990/` default username: `admin`, password: `admin`) or
directly calling: `curl <IP>:47989/pin/<PIN>`.

From Moonlight open the `Desktop` app, from there you should be able to
see your X11 apps running!

=== Errors, issues?

* Checkout the xref:troubleshooting.adoc[troubleshooting] page first
* https://github.com/games-on-whales/gow/issues/new[Open an issue on Github]
* Reach out on the dedicated `#unraid` channel on https://discord.gg/kRGUDHNHt2[Discord]
