== Overview

*Games on Whales (GOW)* lets you stream games (and GUI) running on
Docker with HW acceleration and low latency.

The basic idea is that a
https://en.wikipedia.org/wiki/Server_(computing)[server] can stream
games to clients the same way you play a video on Youtube. There are a
lot of supported clients already such as: mobile phones, laptops,
desktops, and even the Nintendo Switch!

A server is not necessary a https://upload.wikimedia.org/wikipedia/commons/6/69/Wikimedia_Foundation_Servers-8055_35.jpg[gigantic beast of a machine], it can be: a laptop, a normal desktop machine, or even something smaller and compact like a Raspberry PI (https://github.com/games-on-whales/gow/issues/20[in theory]).
Generally, you should be able to pick any OS that supports
https://en.wikipedia.org/wiki/Docker_(software)[Docker] and start using
GOW!

=== How does it work?

We bring together a few different components:

* https://moonlight-stream.org/[Moonlight]: An open source
implementation of NVIDIA’s GameStream protocol. You can stream your
collection of PC games from your GameStream-compatible PC to any
supported device and play them remotely
* https://github.com/loki-47-6F-64/sunshine[Sunshine]: An opensource
Gamestream host for Moonlight. This gives us the ability to stream from
a Linux box since it’s not tied to the proprietary Nvidia GameStream
(Windows only and not opensource)
* https://en.wikipedia.org/wiki/Docker_(software)[Docker]: The platform
that we use in order to deliver software packages (called containers)
that you can easily run without having to manually install and configure
everything
* https://en.wikipedia.org/wiki/X.Org_Server[Xorg]: The window system
that we use in order to manage and display graphical applications
(https://en.wikipedia.org/wiki/Graphical_user_interface[GUI])
* https://en.wikipedia.org/wiki/PulseAudio[PulseAudio]: The software
that will manage audio for our GUIs
* https://en.wikipedia.org/wiki/RetroArch[RetroArch]: An open source,
cross-platform frontend for emulators, game engines, and more!

image::ROOT:gow-diagram.svg[]

Head over to the xref:components-overview.adoc[components overview] if you are interested in how these pieces of software are tied together by GOW
