:experimental:

= Troubleshooting

Here’s a list of common problems and their solutions.

TIP: If you're having trouble with something and you don't see it mentioned, or
if you need more help solving your problem, feel free to
https://github.com/games-on-whales/gow/issues/new[open an issue] or
https://discord.gg/kRGUDHNHt2[reach out on Discord]!

IMPORTANT: In order to be able to stream your desktop, you must meet the xref:monitor.adoc[Monitor requirements].

== Lag, slow, missing frames

You can see more stats in Moonlight during the streaming if you press
kbd:[Ctrl+Alt+Shift+S] (see:
https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#keyboardmousegamepad-input-options[all
keyboard options]).

== mkdir: cannot create directory `/home/retro/sunshine/': Permission denied

This means that your `local_state` folder as defined in the `user.env` file
is not owned by user 1000. You can fix this by:

[source,bash]
....
sudo chown -R 1000:1000 local_state
....

== I can use my mouse and keyboard but my gamepad doesn’t work

If keyboard and mouse are working it means that `uinput`, `Xorg` and `Sunshine`
are correctly working.

Gamepad devices are created by `Sunshine` on connection, only if the client
has one attached. Gamepads are not handled by `Xorg` as input devices; instead
they are directly accessed by the app that wants to use them.  That’s why on
containers that use gamepads have to run in `privileged` mode.

[source,yaml]
----
network_mode: ${UDEVD_NETWORK}
privileged: true
----

== RetroArch is missing icons!

TIP: Using the keyboard you can move using the arrows and get back to the
previous menu by pressing backspace

From the *Main Menu* > *Online Updater* select:

* Update Core Info Files
* Update assets

Press kbd:[F] to toggle fullscreen if you need to.

== How can I get the full logs of Xorg?

Xorg is logging more than what you can see from the command line; you can get
the full log file at `/var/log/Xorg.0.log` from inside the Docker container.
Running the following should copy it to your current directory, even if the
container is no longer running:

[source,bash]
....
docker cp gow-xorg-1:/var/log/Xorg.0.log .
....

NOTE: If you're running in headless mode, it's likely that the file will be
called `Xorg.99.log` instead of `Xorg.0.log`.

== Xorg: Failed to acquire modesetting permission

I’m still not sure about this one, it happened to me when trying to
start GOW on a Desktop system when the screen was locked. Unlocking the
screen first and then running GOW solved the issue for me.

https://wiki.archlinux.org/title/Kernel_mode_setting#Disabling_modesetting[Disabling
modesetting] might be another way to get around it.
