= Platforms

In the Games on Whales system, the "platform" is the component that provides
system-level services like Xorg, PulseAudio, and udev. We provide two options;
"Host Desktop", which uses the services already provided on the host system,
and "Headless", which launches those services in Docker containers.  The goal
of this page is to help you choose which one is best for your situation.

== The Decision _May_ be Made For You

Before we get to analyzing the pros and cons of each approach, we should first
address the "elephant in the room" (as it were): it can be tricky, or even
impossible, to run two separate instances of Xorg on the same computer.  So, if
you're looking to host GoW on a system that _already has_ a desktop, and
therefore a running Xorg server, it may be that your only option is to run in
"Host Desktop" mode.

== Host Desktop mode

In this mode, only the streaming server and the applications are containerized.
That may seem like a big loss, but there are still many benefits of
containerizing applications as much as possible:

* It’s easy to control how much CPU and memory to allocate to each app that
runs via Docker
* You don’t have to manage installation scripts, dependency conflicts, or
updates -- we'll handle all of that for you
* You can easily delete all files created by the application simply by removing
the container
* It’s easier to backup configuration files and state

You may also want to check out
https://github.com/mviereck/x11docker[x11docker]: a project focused on running
GUI apps on top of your existing desktop environment.

== Headless mode

This is where GoW really shines!

We’ll take care of running and configuring:

* A desktop environment
** With audio
** Inside Docker
** That can support HW acceleration
* And with a streaming solution that:
** Is low latency
** Supports keyboard, mouse and gamepads
** Can be hardware accelerated
** *!!!*

On top of that foundation layer you can run most of the GUI applications
out there and even games!



