= Windows

Given the popularity of Windows as a desktop OS, it's natural to wonder if the
Games on Whales system can be run on Windows.  Unfortunately, as of right now,
the answer is "no, not really".  There are a couple of reasons why:

* Windows as a Server OS
+
Although Windows _is_ popular as a desktop OS, and there are certainly many
server solutions built on top of Windows, it really isn't a very common server
OS in home/hobbyist setups.
* Docker on Windows
+
Docker on Windows requires an extra layer of virtualization that can slow
things down, and even cause extra headaches, particularly when networking is
involved.
* WSL2
+
WSL2 is missing the `uinput` kernel module, and although we _have_ been able to
build the module ourselves, Xorg still fails to launch after doing so. That
_should_ be a solvable problem, but it will require some investigation to get
going.

For those reasons, we believe that on Windows, your best bet is to just install
Sunshine and other applications like you normally would, even though it means
foregoing the benefits of containerization.  Having said that, we're open to
the idea that that may not always be the case, and we're open to new ideas and
efforts to make progress on running GoW on Windows.
https://github.com/games-on-whales/gow/issues/13[You can follow the current
status here]
