#!/usr/bin/env python3
"""Generate ROM library configs for ES-DE, Pegasus, and RetroArch (Games on Whales)."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from rom_platforms import (
    CUSTOM_SCRIPT_LAUNCHERS,
    CUSTOM_SCRIPTS_ESDE,
    LAUNCHERS_PROFILE_DIR,
    PLATFORM_STANDALONE_COMMANDS,
    PLATFORMS,
    ROM_FOLDER_ALIASES,
    launcher_description,
)


def iter_platforms(roms_dir: Path | None, only_existing: bool, launcher_only: bool):
    for folder in sorted(PLATFORMS):
        fullname, theme, extensions, has_launcher = PLATFORMS[folder]
        if launcher_only and not has_launcher:
            continue
        if only_existing and roms_dir is not None:
            if not (roms_dir / folder).is_dir():
                continue
        yield folder, fullname, theme, extensions, has_launcher


def _esde_system_block(
    folder: str,
    fullname: str,
    theme: str,
    extensions: str,
    launcher_folder: str,
) -> str:
    command_lines = [
        f'        <command label="Games on Whales">{LAUNCHERS_PROFILE_DIR}/rom_launcher.sh {launcher_folder} %ROM%</command>'
    ]
    for label, cmd in PLATFORM_STANDALONE_COMMANDS.get(launcher_folder, []):
        command_lines.append(f'        <command label="{label}">{cmd}</command>')
    commands_xml = "\n".join(command_lines)
    return f"""    <system>
        <name>{folder}</name>
        <fullname>{fullname}</fullname>
        <path>%ROMPATH%/{folder}</path>
        <extension>{extensions}</extension>
{commands_xml}
        <platform>{theme}</platform>
        <theme>{theme}</theme>
    </system>"""


def generate_esde(roms_dir: Path | None, only_existing: bool, include_aliases: bool = True) -> str:
    blocks = [CUSTOM_SCRIPTS_ESDE]
    seen_names: set[str] = set()

    for folder, fullname, theme, extensions, _ in iter_platforms(
        roms_dir, only_existing, launcher_only=True
    ):
        blocks.append(_esde_system_block(folder, fullname, theme, extensions, folder))
        seen_names.add(folder)

    if include_aliases and roms_dir is not None and roms_dir.is_dir():
        for alias_folder, launcher_folder in sorted(ROM_FOLDER_ALIASES.items()):
            if alias_folder in seen_names or alias_folder in PLATFORMS:
                continue
            if launcher_folder not in PLATFORMS or not PLATFORMS[launcher_folder][3]:
                continue
            if not (roms_dir / alias_folder).is_dir():
                continue
            _fullname, theme, extensions, _ = PLATFORMS[launcher_folder]
            display = f"{alias_folder} ({_fullname})"
            blocks.append(_esde_system_block(alias_folder, display, theme, extensions, launcher_folder))
            seen_names.add(alias_folder)

    body = "\n\n".join(blocks)
    return (
        '<?xml version="1.0"?>\n'
        "<!-- Generated by generate_rom_library_configs.py (Games on Whales) -->\n"
        "<systemList>\n"
        f"{body}\n"
        "</systemList>\n"
    )


def generate_pegasus_game_dirs(roms_dir: Path | None, only_existing: bool) -> str:
    lines = ["/cfg/app"]
    for folder, _, _, _, _ in iter_platforms(roms_dir, only_existing, launcher_only=False):
        lines.append(f"/ROMs/{folder}")
    if roms_dir is not None and roms_dir.is_dir():
        for child in sorted(roms_dir.iterdir()):
            if not child.is_dir() or child.name in PLATFORMS or child.name.startswith("."):
                continue
            lines.append(f"/ROMs/{child.name}")
    # De-dupe while preserving order
    seen: set[str] = set()
    unique: list[str] = []
    for line in lines:
        if line not in seen:
            seen.add(line)
            unique.append(line)
    return "\n".join(unique) + "\n"


def generate_pegasus_metadata(roms_dir: Path | None, only_existing: bool) -> str:
    blocks: list[str] = [
        "# Generated ROM collections (Games on Whales)",
        "# Launcher scripts live under Custom Scripts / Applications in the static metadata file.",
        "",
    ]
    for folder, fullname, _, _, has_launcher in iter_platforms(
        roms_dir, only_existing, launcher_only=True
    ):
        if not has_launcher:
            continue
        blocks.extend(
            [
                f"collection: {fullname}",
                f"shortname: {folder}",
                f"launch: /Applications/launchers/rom_launcher.sh {folder} \"{{file.path}}\"",
                "files:",
                f"  /ROMs/{folder}",
                "",
            ]
        )
    return "\n".join(blocks)


def generate_retroarch_playlists(roms_dir: Path | None, only_existing: bool) -> str:
    """Emit RetroArch playlist stubs (optional; RA also browses /ROMs directly)."""
    lines = ["# RetroArch playlist paths (Games on Whales)", ""]
    for folder, fullname, _, _, has_launcher in iter_platforms(
        roms_dir, only_existing, launcher_only=True
    ):
        if not has_launcher:
            continue
        lines.append(f"# {fullname}")
        lines.append(f"playlist_{folder}_path = \"/ROMs/{folder}\"")
        lines.append("")
    return "\n".join(lines)


LAUNCHERS_CONTAINER_DIR = "/Applications/launchers"
STOCK_LAUNCHER_PATHS = {
    f"{LAUNCHERS_PROFILE_DIR}/{name}" for name in CUSTOM_SCRIPT_LAUNCHERS
} | {
    f"{LAUNCHERS_CONTAINER_DIR}/{name}" for name in CUSTOM_SCRIPT_LAUNCHERS
}


def _launcher_path(script_name: str) -> str:
    return f"{LAUNCHERS_PROFILE_DIR}/{script_name}"


def _launcher_scripts(launchers_dir: Path | None) -> list[str]:
    """Return launcher script basenames (excluding rom_launcher.sh), preferring stock GOW set."""
    found: set[str] = set()
    if launchers_dir is not None and launchers_dir.is_dir():
        found = {
            p.name
            for p in launchers_dir.glob("*.sh")
            if p.is_file() and p.name != "rom_launcher.sh"
        }
    names = list(CUSTOM_SCRIPT_LAUNCHERS)
    for name in sorted(found):
        if name not in names:
            names.append(name)
    return names


def _launcher_display(name: str) -> tuple[str, str]:
    if name in CUSTOM_SCRIPT_LAUNCHERS:
        return CUSTOM_SCRIPT_LAUNCHERS[name], launcher_description(name)
    stem = Path(name).stem.replace("_", " ").title()
    return stem, f"Launch {stem}"


def _custom_scripts_game_xml(script_name: str) -> str:
    display_name, desc = _launcher_display(script_name)
    path = _launcher_path(script_name)
    return f"""	<game>
		<path>{path}</path>
		<name>{display_name}</name>
		<desc>{desc}</desc>
		<genre>Launcher</genre>
	</game>"""


def generate_esde_custom_scripts_gamelist(launchers_dir: Path | None) -> str:
    """Gamelist entries for the ES-DE Custom Scripts platform (emulator launchers)."""
    games = [_custom_scripts_game_xml(script_name) for script_name in _launcher_scripts(launchers_dir)]
    body = "\n".join(games)
    return (
        '<?xml version="1.0"?>\n'
        "<!-- Generated by generate_rom_library_configs.py (Custom Scripts launchers) -->\n"
        "<gameList>\n"
        f"{body}\n"
        "</gameList>\n"
    )


def merge_esde_custom_scripts_gamelist(existing_file: Path, launchers_dir: Path) -> str:
    """Refresh stock launcher entries; preserve user-added Custom Scripts."""
    custom_blocks: list[str] = []
    if existing_file.is_file():
        text = existing_file.read_text(encoding="utf-8")
        for block in re.findall(r"\t<game>.*?</game>", text, flags=re.DOTALL):
            path_match = re.search(r"<path>([^<]+)</path>", block)
            if path_match and path_match.group(1) in STOCK_LAUNCHER_PATHS:
                continue
            if path_match and not (
                path_match.group(1).startswith(f"{LAUNCHERS_PROFILE_DIR}/")
                or path_match.group(1).startswith(f"{LAUNCHERS_CONTAINER_DIR}/")
            ):
                continue
            custom_blocks.append(block)
    else:
        text = '<?xml version="1.0"?>\n<gameList>\n</gameList>\n'

    stock_blocks = [_custom_scripts_game_xml(name) for name in _launcher_scripts(launchers_dir)]
    all_blocks = stock_blocks + custom_blocks
    body = "\n".join(all_blocks)
    return (
        '<?xml version="1.0"?>\n'
        "<!-- Generated by generate_rom_library_configs.py (Custom Scripts launchers) -->\n"
        "<gameList>\n"
        f"{body}\n"
        "</gameList>\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate GOW ROM library frontend configs")
    parser.add_argument(
        "--format",
        choices=(
            "esde",
            "esde-custom-scripts-gamelist",
            "pegasus-game-dirs",
            "pegasus-metadata",
            "retroarch-hints",
        ),
        required=True,
    )
    parser.add_argument("--roms-dir", type=Path, help="ROM library root (/ROMs in container)")
    parser.add_argument(
        "--launchers-dir",
        type=Path,
        help="Directory with *.sh emulator launchers (/Applications/launchers in container)",
    )
    parser.add_argument(
        "--merge-gamelist",
        type=Path,
        help="With esde-custom-scripts-gamelist: merge into this gamelist.xml path",
    )
    parser.add_argument(
        "--only-existing",
        action="store_true",
        help="Only emit platforms with a subdirectory under --roms-dir",
    )
    parser.add_argument(
        "--include-aliases",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Emit ES-DE systems for alternate ROM folder names (megadrive, sfc, mame, …)",
    )
    args = parser.parse_args()

    if args.only_existing and not args.roms_dir:
        print("--only-existing requires --roms-dir", file=sys.stderr)
        return 2

    roms_dir = args.roms_dir
    if roms_dir is not None and not roms_dir.is_dir():
        print(f"ROM directory not found: {roms_dir}", file=sys.stderr)
        return 1

    generators = {
        "pegasus-game-dirs": generate_pegasus_game_dirs,
        "pegasus-metadata": generate_pegasus_metadata,
        "retroarch-hints": generate_retroarch_playlists,
    }

    if args.format == "esde":
        sys.stdout.write(generate_esde(roms_dir, args.only_existing, args.include_aliases))
        return 0

    if args.format == "esde-custom-scripts-gamelist":
        launchers_dir = args.launchers_dir or Path("/Applications/launchers")
        if args.merge_gamelist:
            merged = merge_esde_custom_scripts_gamelist(args.merge_gamelist, launchers_dir)
            sys.stdout.write(merged)
            return 0
        if not launchers_dir.is_dir():
            print(f"Launchers directory not found: {launchers_dir}", file=sys.stderr)
            return 1
        sys.stdout.write(generate_esde_custom_scripts_gamelist(launchers_dir))
        return 0

    sys.stdout.write(generators[args.format](roms_dir, args.only_existing))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
