#########################
# firefox.yml
#########################
#
# This container runs Firefox

services:
  # ####################
  # An example of running an unprivileged X11 app in this environment.
  firefox:
    image: ghcr.io/games-on-whales/firefox:edge
#   build:
#     context: ./images/firefox
#     args:
#       BASE_IMAGE: ${BUILD_BASE_IMAGE}
#       BASE_APP_IMAGE: ${BUILD_BASE_APP_IMAGE}
    runtime: ${DOCKER_RUNTIME}
    volumes:
      - ${XORG_SOCKET}:/tmp/.X11-unix
      - ${PULSE_SOCKET_HOST}:${PULSE_SOCKET_GUEST}

    env_file:
      - config/common.env
      - config/xorg.env
      # run-gow: gpu_env

    environment:
      LOG_LEVEL: info


