#########################
# lutris.yml
#########################
#
# This container runs Lutris

services:
  ####################
  lutris:
#   image: ghcr.io/games-on-whales/lutris:edge
    build:
      context: ./images/lutris
      args:
        BASE_IMAGE: ${BUILD_BASE_IMAGE}
        BASE_APP_IMAGE: ${BUILD_BASE_APP_IMAGE}
    runtime: ${DOCKER_RUNTIME}
    privileged: true
    network_mode: ${UDEVD_NETWORK}
    volumes:
      # Followings are needed in order to get joystick support
      - /dev/input:/dev/input:ro
      - udev:/run/udev:ro
      # Xorg socket in order to get the screen
      - ${XORG_SOCKET}:/tmp/.X11-unix
      # Pulse socket, audio
      - ${PULSE_SOCKET_HOST}:${PULSE_SOCKET_GUEST}
      # Home directory: client, games, downloads, etc
      - ${local_state}/:/home/retro/
      # - /mnt/user/appdata/builds/gow/sudo-test:/etc/sudoers.d/retro:ro
      # The following is needed by the webview otherwise you'll get Less than
      # 64MB of free space in temporary directory
      # (https://github.com/microsoft/vscode/issues/111729#issuecomment-737399692)
      # TODO: why shm_size doesn't work ??????
      - type: tmpfs
        target: /dev/shm
        tmpfs:
            size: ${SHM_SIZE}
    ipc: ${SHARED_IPC}  # Needed for MIT-SHM, removing this should cause a performance hit see https://github.com/jessfraz/dockerfiles/issues/359

    env_file:
      - config/common.env
      - config/xorg.env
      # run-gow: gpu_env

    environment:
      PROTON_LOG: 1
