# Pushes the contents of the repo to the Codeberg mirror
name: Repo Mirror
on: [ push ]
jobs:
  codeberg:
    # This job will only run if the repository is 'games-on-whales/gow'
    if: github.repository == 'games-on-whales/gow'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: "git@codeberg.org:games-on-whales/gow.git"
          ssh_private_key: ${{ secrets.CODEBERG_SSH }}